version: '3.0'
services:
  dante:
    build:
      context: dante
      dockerfile: Dockerfile
    image: kotfenix/tgdante2:latest
    hostname: dante
    container_name: dante
    volumes:
      - ./etc:/etc
    ports:
      - "1080:1080"
    network_mode: "host"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped
